import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  StatusBar,
  TextInput,
  Dimensions,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { collection, doc, getDoc, setDoc, getDocs } from 'firebase/firestore';
import { db } from '../config/firebase';
import { useTranslation } from 'react-i18next';
import { COLORS } from '../theme';
import CustomHeader from '../components/CustomHeader';

const { width } = Dimensions.get('window');

// ----------------------------------------------------------------------
// THE BEST AI COMMAND/PROMPT FOR GENERATING FULL MANTRAS & CHALISAS
// Use this system prompt when you connect to Gemini/OpenAI API:
export const AI_MANTRA_PROMPT = `
You are an expert Vedic Scholar and Spiritual Guide. 
The user will ask for a Mantra, Stotram, Chalisa, or Aarti (e.g., 'Hanuman Chalisa' or 'Shiva Mantra').
Your strict task is to provide the **COMPLETE and FULL text** of what they requested in beautifully formatted Hindi/Sanskrit (Devanagari script), followed by a brief English summary.
DO NOT provide just a short snippet or 2 lines. If they ask for Hanuman Chalisa, give all 40 Chaupais and Dohas.
DO NOT add any conversational filler. Only return the sacred text and the meaning.
`;
// ----------------------------------------------------------------------

const STATIC_MANTRAS = [
  { id: 'gayatri', name: 'Gayatri Mantra', text: 'ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्।', type: 'Universal', icon: '☀️' },
  { id: 'mahamrityunjaya', name: 'Mahamrityunjaya', text: 'ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्। उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय माऽमृतात्॥', type: 'Shiva', icon: '🔱' },
  { id: 'ganesh', name: 'Ganesh Mantra', text: 'ॐ गण गणपतये नमः', type: 'Ganesha', icon: '🐘' },
];

export default function MantraScreen({ onBack, user, onSelectMantra }) {
  const { t, i18n } = useTranslation();
  const [customMantras, setCustomMantras] = useState([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [newMantraName, setNewMantraName] = useState('');
  const [loading, setLoading] = useState(true);

  const isEnglish = i18n.language === 'en';

  useEffect(() => {
    fetchSharedMantras();
  }, []);

  const fetchSharedMantras = async () => {
    try {
      const querySnapshot = await getDocs(collection(db, 'ai_mantras'));
      const fetched = [];
      querySnapshot.forEach((doc) => {
        fetched.push({ id: doc.id, ...doc.data() });
      });
      setCustomMantras(fetched);
    } catch (error) {
      console.log("Error fetching mantras:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleMantraClick = (mantra) => {
    onSelectMantra(mantra);
  };

  const generateMantra = async () => {
    if (!user) {
      Alert.alert("Login Required", "Please login to generate custom mantras.");
      return;
    }

    if (!newMantraName.trim()) {
      Alert.alert("Input Needed", "Please enter a deity, mantra, or chalisa name.");
      return;
    }

    const mantraId = newMantraName.toLowerCase().trim().replace(/\s/g, '_');
    const mantraRef = doc(db, 'ai_mantras', mantraId);
    
    setIsGenerating(true);
    try {
      const mantraSnap = await getDoc(mantraRef);

      if (mantraSnap.exists()) {
        setIsGenerating(false);
        const existingData = mantraSnap.data();
        Alert.alert(
          "Already Generated",
          "This has already been generated by AI and is ready to view!",
          [{ text: "View Now", onPress: () => {
            setNewMantraName('');
            handleMantraClick(existingData);
          }}]
        );
        return;
      }

      // Simulate full AI Generation logic using the prompt rules above
      setTimeout(async () => {
        let mockMantraText = `ॐ ${newMantraName} नमः\n\n(This is a generated mantra. Connect an AI API with the AI_MANTRA_PROMPT to get full live text.)`;
        let icon = '✨';
        
        const lowerName = newMantraName.toLowerCase();
        if (lowerName.includes('hanuman chalisa')) {
          icon = '🐒';
          mockMantraText = `॥ दोहा ॥
श्रीगुरु चरन सरोज रज निज मनु मुकुरु सुधारि।
बरनऊँ रघुबर बिमल जसु जो दायकु फल चारि॥
बुद्धिहीन तनु जानिके सुमिरौं पवन-कुमार।
बल बुधि बिद्या देहु मोहिं हरहु कलेस बिकार॥

॥ चौपाई ॥
जय हनुमान ज्ञान गुन सागर। जय कपीस तिहुँ लोक उजागर॥
राम दूत अतुलित बल धामा। अंजनि-पुत्र पवनसुत नामा॥
महाबीर बिक्रम बजरंगी। कुमति निवार सुमति के संगी॥
कंचन बरन बिराज सुबेसा। कानन कुंडल कुंचित केसा॥
हाथ बज्र औ ध्वजा बिराजै। काँधे मूँज जनेऊ साजै॥
संकर सुवन केसरी नंदन। तेज प्रताप महा जग बंदन॥
बिद्यावान गुनी अति चातुर। राम काज करिबे को आतुर॥
प्रभु चरित्र सुनिबे को रसिया। राम लखन सीता मन बसिया॥
सूक्ष्म रूप धरि सियहिं दिखावा। बिकट रूप धरि लंक जरावा॥
भीम रूप धरि असुर सँहारे। रामचंद्र के काज सँवारे॥
लाय सजीवन लखन जियाये। श्रीरघुबीर हरषि उर लाये॥
रघुपति कीन्ही बहुत बड़ाई। तुम मम प्रिय भरतहि सम भाई॥
सहस बदन तुम्हरो जस गावैं। अस कहि श्रीपति कंठ लगावैं॥
सनकादिक ब्रह्मादि मुनीसा। नारद सारद सहित अहीसा॥
जम कुबेर दिगपाल जहाँ ते। कबि कोबिद कहि सके कहाँ ते॥
तुम उपकार सुग्रीवहिं कीन्हा। राम मिलाय राज पद दीन्हा॥
तुम्हरो मंत्र बिभीषन माना। लंकेस्वर भए सब जग जाना॥
जुग सहस्र जोजन पर भानू। लील्यो ताहि मधुर फल जानू॥
प्रभु मुद्रिका मेलि मुख माहीं। जलधि लाँघि गये अचरज नाहीं॥
दुर्गम काज जगत के जेते। सुगम अनुग्रह तुम्हरे तेते॥
राम दुआरे तुम रखवारे। होत न आग्या बिनु पैसारे॥
सब सुख लहै तुम्हारी सरना। तुम रक्षक काहू को डरना॥
आपन तेज सम्हारो आपै। तीनों लोक हाँक तें काँपै॥
भूत पिसाच निकट नहिं आवै। महाबीर जब नाम सुनावै॥
नासै रोग हरै सब पीरा। जपत निरंतर हनुमत बीरा॥
संकट तें हनुमान छुड़ावै। मन क्रम बचन ध्यान जो लावै॥
सब पर राम तपस्वी राजा। तिन के काज सकल तुम साजा॥
और मनोरथ जो कोई लावै। सोइ अमित जीवन फल पावै॥
चारों जुग परताप तुम्हारा। है परसिद्ध जगत उजियारा॥
साधु संत के तुम रखवारे। असुर निकंदन राम दुलारे॥
अष्ट सिद्धि नौ निधि के दाता। अस बर दीन जानकी माता॥
राम रसायन तुम्हरे पासा। सदा रहो रघुपति के दासा॥
तुम्हरे भजन राम को पावै। जनम जनम के दुख बिसरावै॥
अंत काल रघुबर पुर जाई। जहाँ जन्म हरि-भक्त कहाई॥
और देवता चित्त न धरई। हनुमत सेइ सर्ब सुख करई॥
संकट कटै मिटै सब पीरा। जो सुमिरै हनुमत बलबीरा॥
जय जय जय हनुमान गोसाईं। कृपा करहु गुरुदेव की नाईं॥
जो सत बार पाठ कर कोई। छूटहि बंदि महा सुख होई॥
जो यह पढ़ै हनुमान चालीसा। होय सिद्धि साखी गौरीसा॥
तुलसीदास सदा हरि चेरा। कीजै नाथ हृदय मँह डेरा॥

॥ दोहा ॥
पवनतनय संकट हरन मंगल मूरति रूप।
राम लखन सीता सहित हृदय बसहु सुर भूप॥`;
        } else if (lowerName.includes('shiv tandav')) {
          icon = '🔱';
          mockMantraText = `जटाटवीगलज्जलप्रवाहपावितस्थले
गलेऽवलम्ब्य लम्बितां भुजङ्गतुङ्गमालिकाम्।
डमड्डमड्डमड्डमन्निनादवड्डमर्वयं
चकार चण्डताण्डवं तनोतु नः शिवः शिवम्॥१॥

जटाकटाहसम्भ्रमभ्रमन्निलिम्पनिर्झरी-
विलोलवीचिवल्लरीविराजमानमूर्धनि।
धगद्धगद्धगज्ज्वलल्ललाटपट्टपावके
किशोरचन्द्रशेखरे रतिः प्रतिक्षणं मम॥२॥

धराधरेन्द्रनन्दिनीविलासबन्धुबन्धुर-
स्फुरद्दिगन्तसन्ततिप्रमोदमानमानसे।
कृपाकटाक्षधोरणीनिरुद्धदुर्धरापदि
क्वचिद्दिगम्बरे मनो विनोदमेतु वस्तुनि॥३॥

जटाभुजङ्गपिङ्गलस्फुरत्फणामणिप्रभा-
कदम्बकुङ्कुमद्रवप्रलिप्तदिग्वधूमुखे।
मदान्धसिन्धुरस्फुरत्त्वगुत्तरीयमेदुरे
मनो विनोदमद्भुतं बिभर्तु भूतभर्तरि॥४॥

सहस्रलोचनप्रभृत्यशेषलेखशेखर-
प्रसूनधूलिधोरणीविधूसराङ्घ्रिपीठभूः।
भुजङ्गराजमालया निबद्धजाटजूटकः
श्रियै चिराय जायतां चकोरबन्धुशेखरः॥५॥

ललाटचत्वरज्वलद्धनञ्जयस्फुलिङ्गभा-
निपीतपञ्चसायकं नमन्निलिम्पनायकम्।
सुधामयूखलेखया विराजमानशेखरं
महाकपालिसम्पदे शिरोजटालमस्तु नः॥६॥`;
        }

        const newMantraData = {
          name: newMantraName,
          text: mockMantraText,
          generatedBy: user.email,
          createdAt: new Date().getTime(),
          type: 'AI Generated',
          icon: icon
        };

        await setDoc(mantraRef, newMantraData);

        setCustomMantras([newMantraData, ...customMantras]);
        setNewMantraName('');
        setIsGenerating(false);
        Alert.alert("Sacred Text Ready", "AI has completely generated the sacred text for you!", [
          { text: "Read Now", onPress: () => handleMantraClick(newMantraData) }
        ]);
      }, 2500);

    } catch (error) {
      console.error(error);
      setIsGenerating(false);
    }
  };

  const allMantras = [...STATIC_MANTRAS, ...customMantras];
  const filteredMantras = allMantras.filter(m => 
    m.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" />
      <LinearGradient colors={['#FDFCFB', '#FFF5E6']} style={StyleSheet.absoluteFill} />
      
      <CustomHeader title="Sacred Texts" onBack={onBack} />

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        
        {/* Dynamic AI Generator Box */}
        <LinearGradient colors={['#800000', COLORS.primary]} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.aiBox}>
          <View style={styles.aiPattern} />
          <Text style={styles.aiTitle}>Vedic AI Generator ✨</Text>
          <Text style={styles.aiSub}>Enter any Chalisa, Stotram, or Mantra name and our AI will fetch the complete authentic text.</Text>
          
          <View style={styles.inputWrapper}>
            <TextInput
              style={styles.aiInput}
              placeholder="e.g. Hanuman Chalisa"
              placeholderTextColor="rgba(255,255,255,0.5)"
              value={newMantraName}
              onChangeText={setNewMantraName}
            />
            <TouchableOpacity 
              style={styles.generateBtn} 
              onPress={generateMantra}
              disabled={isGenerating}
              activeOpacity={0.8}
            >
              {isGenerating ? (
                <ActivityIndicator color={COLORS.primary} />
              ) : (
                <Text style={styles.generateText}>Generate</Text>
              )}
            </TouchableOpacity>
          </View>
        </LinearGradient>

        {/* Search Bar */}
        <View style={styles.searchContainer}>
          <Text style={styles.searchIcon}>🔍</Text>
          <TextInput
            style={styles.searchInput}
            placeholder="Search mantras & texts..."
            placeholderTextColor="#999"
            value={searchQuery}
            onChangeText={setSearchQuery}
          />
        </View>

        {loading ? (
          <ActivityIndicator size="large" color={COLORS.primary} style={{marginTop: 50}} />
        ) : (
          filteredMantras.map((mantra, idx) => (
            <TouchableOpacity 
              key={idx} 
              style={styles.mantraCard}
              onPress={() => handleMantraClick(mantra)}
              activeOpacity={0.9}
            >
              <View style={styles.cardHeader}>
                <View style={styles.cardTitleRow}>
                  <View style={styles.iconCircle}>
                    <Text style={styles.mantraIcon}>{mantra.icon || '📿'}</Text>
                  </View>
                  <Text style={styles.mantraName}>{mantra.name}</Text>
                </View>
                <View style={[styles.typeBadge, mantra.type === 'AI Generated' && {backgroundColor: 'rgba(255, 153, 51, 0.15)'}]}>
                  <Text style={[styles.typeText, mantra.type === 'AI Generated' && {color: COLORS.accent}]}>{mantra.type}</Text>
                </View>
              </View>
              
              <View style={styles.textPreviewBox}>
                <Text numberOfLines={3} style={styles.mantraSnippet}>{mantra.text}</Text>
                <LinearGradient colors={['transparent', '#FFF']} style={styles.fadeOverlay} />
              </View>
              
              <View style={styles.readMoreRow}>
                <Text style={styles.readMoreText}>Read Full Text</Text>
                <Text style={styles.readMoreArrow}>→</Text>
              </View>
            </TouchableOpacity>
          ))
        )}
        <View style={{height: 60}} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { padding: 20 },
  
  /* AI Box */
  aiBox: { borderRadius: 30, padding: 25, elevation: 15, shadowColor: COLORS.primary, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.3, shadowRadius: 15, marginBottom: 30, overflow: 'hidden' },
  aiPattern: { position: 'absolute', right: -50, top: -50, width: 150, height: 150, borderRadius: 75, backgroundColor: 'rgba(255,255,255,0.05)' },
  aiTitle: { fontSize: 22, fontWeight: '900', color: '#FFF', marginBottom: 8 },
  aiSub: { fontSize: 13, color: 'rgba(255,255,255,0.8)', lineHeight: 20, marginBottom: 20, paddingRight: 20 },
  inputWrapper: { flexDirection: 'row', alignItems: 'center' },
  aiInput: { flex: 1, backgroundColor: 'rgba(255,255,255,0.15)', borderRadius: 15, paddingHorizontal: 20, height: 55, color: '#FFF', fontSize: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
  generateBtn: { backgroundColor: '#FFF', paddingHorizontal: 25, height: 55, borderRadius: 15, marginLeft: 12, justifyContent: 'center', elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 5 },
  generateText: { color: COLORS.primary, fontWeight: '900', fontSize: 15 },
  
  /* Search */
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', height: 60, borderRadius: 20, paddingHorizontal: 20, elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 10, marginBottom: 25, borderWidth: 1, borderColor: '#F0F0F0' },
  searchIcon: { fontSize: 20, marginRight: 15 },
  searchInput: { flex: 1, fontSize: 16, color: '#333' },
  
  /* Mantra Card */
  mantraCard: { backgroundColor: '#FFF', borderRadius: 25, padding: 20, marginBottom: 20, elevation: 6, shadowColor: '#000', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.08, shadowRadius: 10, borderWidth: 1, borderColor: 'rgba(0,0,0,0.02)' },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  cardTitleRow: { flexDirection: 'row', alignItems: 'center' },
  iconCircle: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#FFF5E6', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  mantraIcon: { fontSize: 22 },
  mantraName: { fontSize: 18, fontWeight: '900', color: COLORS.primary },
  typeBadge: { backgroundColor: '#F5F5F5', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 10 },
  typeText: { fontSize: 10, fontWeight: '900', color: '#666', textTransform: 'uppercase' },
  
  textPreviewBox: { position: 'relative', marginBottom: 15 },
  mantraSnippet: { fontSize: 15, color: '#555', lineHeight: 24, fontStyle: 'italic' },
  fadeOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 30 },
  
  readMoreRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#F5F5F5', paddingTop: 15 },
  readMoreText: { color: COLORS.accent, fontSize: 14, fontWeight: '800' },
  readMoreArrow: { color: COLORS.accent, fontSize: 18, fontWeight: 'bold' },
});
