import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  StatusBar,
  TextInput,
  Dimensions,
  Image,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { useTranslation } from 'react-i18next';
import { doc, getDoc } from 'firebase/firestore';
import { db } from '../config/firebase';
import { COLORS } from '../theme';
import CustomHeader from '../components/CustomHeader';

const { width } = Dimensions.get('window');

const CATEGORIES = ['All', 'Festivals', 'Home', 'Deities', 'Sanskars'];

const PUJAS = [
  { id: 'ganesh', name: 'Ganesh Puja', nameHi: 'गणेश पूजा', icon: '🐘', color: ['#FFF5F5', '#FFE0E0'], cat: 'Deities' },
  { id: 'lakshmi', name: 'Lakshmi Puja', nameHi: 'लक्ष्मी पूजा', icon: '💰', color: ['#FFF9F2', '#FFEDD9'], cat: 'Deities' },
  { id: 'satyanarayan', name: 'Satyanarayan Katha', nameHi: 'सत्यनारायण कथा', icon: '📖', color: ['#F5FFF5', '#D9FFD9'], cat: 'Home' },
  { id: 'shiva', name: 'Mahashivratri', nameHi: 'महाशिवरात्रि पूजा', icon: '🔱', color: ['#F5F5FF', '#D9D9FF'], cat: 'Festivals' },
  { id: 'saraswati', name: 'Saraswati Puja', nameHi: 'सरस्वती पूजा', icon: '🎻', color: ['#FFFFF5', '#FFFFD9'], cat: 'Deities' },
  { id: 'durga', name: 'Navratri Durga Puja', nameHi: 'नवरात्रि दुर्गा पूजा', icon: '🦁', color: ['#FFF0F5', '#FFD9E6'], cat: 'Festivals' },
  { id: 'griha', name: 'Griha Pravesh', nameHi: 'गृह प्रवेश', icon: '🏠', color: ['#F0F8FF', '#D9EDFF'], cat: 'Sanskars' },
  { id: 'ram', name: 'Ram Navami', nameHi: 'राम नवमी पूजा', icon: '🏹', color: ['#FFF5EE', '#FFE6D9'], cat: 'Festivals' },
];

export default function PujaVidhiScreen({ onBack, onSelectPuja, user }) {
  const { t, i18n } = useTranslation();
  const [searchQuery, setSearchQuery] = useState('');
  const [activeCat, setActiveCat] = useState('All');
  
  const isEnglish = i18n.language === 'en';
  const currentLang = i18n.language === 'en' ? 'en' : 'hi';
  
  const filteredPujas = PUJAS.filter(puja => {
    const matchesSearch = (isEnglish ? puja.name : puja.nameHi).toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCat = activeCat === 'All' || puja.cat === activeCat;
    return matchesSearch && matchesCat;
  });

  const handlePujaPress = async (puja) => {
    if (!user) {
      Alert.alert("Login Required", isEnglish ? 'Please login to access Puja Vidhi' : 'पूजा विधि देखने के लिए कृपया लॉगिन करें');
      return;
    }

    const pujaRef = doc(db, 'ai_pujas', `${puja.id}_${currentLang}`);
    const pujaSnap = await getDoc(pujaRef);

    if (pujaSnap.exists()) {
      Alert.alert(
        "Already Generated",
        "This Puja Vidhi has already been generated by our AI and is ready to view!",
        [{ text: "View Vidhi", onPress: () => onSelectPuja(puja) }]
      );
      return;
    }

    onSelectPuja(puja);
  };

  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" />
      <CustomHeader title={t('pujaVidhi')} onBack={onBack} />

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}>
        
        {/* AI Hero Banner */}
        <TouchableOpacity 
          style={styles.aiHeroBtn}
          onPress={() => Alert.alert("AI Generator", "Coming soon! AI will generate personalized Puja Vidhis based on your birth chart.")}
          activeOpacity={0.9}
        >
          <LinearGradient colors={[COLORS.primary, '#500000']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.aiHeroGradient}>
            <View style={styles.aiHeroContent}>
              <View>
                <Text style={styles.aiHeroTitle}>AI Custom Puja ✨</Text>
                <Text style={styles.aiHeroSub}>Can't find what you need? Let our Vedic AI craft the perfect Puja Vidhi for you.</Text>
              </View>
              <View style={styles.aiHeroIconBox}>
                <Text style={styles.aiHeroIcon}>🤖</Text>
              </View>
            </View>
          </LinearGradient>
        </TouchableOpacity>

        {/* Search Bar */}
        <View style={styles.searchContainer}>
          <Text style={styles.searchIcon}>🔍</Text>
          <TextInput
            style={styles.searchInput}
            placeholder={isEnglish ? "Search Pujas, Mantras..." : "पूजा खोजें..."}
            placeholderTextColor="#999"
            value={searchQuery}
            onChangeText={setSearchQuery}
          />
        </View>

        {/* Categories Horizontal Scroll */}
        <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.catScroll} contentContainerStyle={styles.catContent}>
          {CATEGORIES.map(cat => (
            <TouchableOpacity 
              key={cat} 
              style={[styles.catBtn, activeCat === cat && styles.catBtnActive]}
              onPress={() => setActiveCat(cat)}
            >
              <Text style={[styles.catText, activeCat === cat && styles.catTextActive]}>{cat}</Text>
            </TouchableOpacity>
          ))}
        </ScrollView>

        {/* Results Grid */}
        <View style={styles.grid}>
          {filteredPujas.map((item) => (
            <TouchableOpacity 
              key={item.id} 
              style={styles.gridItemWrapper}
              onPress={() => handlePujaPress(item)}
              activeOpacity={0.8}
            >
              <LinearGradient colors={item.color} style={styles.gridItem}>
                <View style={styles.iconCircle}>
                  <Text style={styles.gridIcon}>{item.icon}</Text>
                </View>
                <Text style={styles.gridLabel}>{isEnglish ? item.name : item.nameHi}</Text>
                <View style={styles.aiBadge}>
                  <Text style={styles.aiBadgeText}>AI Supported</Text>
                </View>
              </LinearGradient>
            </TouchableOpacity>
          ))}
        </View>

        {filteredPujas.length === 0 && (
          <View style={styles.emptyState}>
            <Text style={styles.emptyIcon}>🪔</Text>
            <Text style={styles.emptyText}>No Pujas found in this category.</Text>
          </View>
        )}

        <View style={{ height: 100 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FDFCFB' },
  scrollContent: { padding: 20 },
  aiHeroBtn: { borderRadius: 25, overflow: 'hidden', elevation: 10, shadowColor: COLORS.primary, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.3, shadowRadius: 15, marginBottom: 25 },
  aiHeroGradient: { padding: 25 },
  aiHeroContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  aiHeroTitle: { color: '#FFF', fontSize: 20, fontWeight: '900', marginBottom: 5 },
  aiHeroSub: { color: 'rgba(255,255,255,0.8)', fontSize: 13, width: width * 0.5, lineHeight: 20, fontWeight: '500' },
  aiHeroIconBox: { width: 60, height: 60, borderRadius: 30, backgroundColor: 'rgba(255,255,255,0.15)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.3)' },
  aiHeroIcon: { fontSize: 30 },
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', height: 60, borderRadius: 20, paddingHorizontal: 20, elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 10, marginBottom: 20, borderWidth: 1, borderColor: '#F0F0F0' },
  searchIcon: { fontSize: 20, marginRight: 15 },
  searchInput: { flex: 1, fontSize: 16, color: '#333' },
  catScroll: { marginBottom: 25 },
  catContent: { paddingRight: 20 },
  catBtn: { paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20, backgroundColor: '#FFF', marginRight: 10, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 4, borderWidth: 1, borderColor: '#EEE' },
  catBtnActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  catText: { fontSize: 14, fontWeight: '700', color: '#666' },
  catTextActive: { color: '#FFF' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  gridItemWrapper: { width: (width - 55) / 2, marginBottom: 15 },
  gridItem: { padding: 20, borderRadius: 25, alignItems: 'center', elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8, borderWidth: 1, borderColor: 'rgba(255,255,255,0.5)', position: 'relative' },
  iconCircle: { width: 60, height: 60, borderRadius: 30, backgroundColor: '#FFF', alignItems: 'center', justifyContent: 'center', marginBottom: 15, elevation: 3, shadowColor: '#000', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.1, shadowRadius: 5 },
  gridIcon: { fontSize: 30 },
  gridLabel: { fontSize: 15, fontWeight: '900', color: COLORS.primary, textAlign: 'center', marginBottom: 5 },
  aiBadge: { marginTop: 8, backgroundColor: 'rgba(255,255,255,0.8)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10 },
  aiBadgeText: { fontSize: 10, color: COLORS.accent, fontWeight: '900' },
  emptyState: { alignItems: 'center', marginTop: 40 },
  emptyIcon: { fontSize: 50, marginBottom: 10, opacity: 0.5 },
  emptyText: { fontSize: 16, color: '#999', fontWeight: '600' },
});
